# Generated by Django 6.0.1 on 2026-01-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=7)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
