# Generated by Django 6.0.1 on 2026-01-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forex_logs.pair'),
            preserve_default=False,
        ),
    ]
