# Generated by Django 6.0.1 on 2026-01-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0002_price_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='note',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
