# Generated by Django 6.0.1 on 2026-01-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0003_price_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'verbose_name_plural': 'Pairs'},
        ),
    ]
