# Generated by Django 6.0.1 on 2026-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0004_alter_pair_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='note',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
