# Generated by Django 6.0.1 on 2026-01-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0005_alter_price_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_close',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_high',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_low',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_open',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
