# Generated by Django 6.0.1 on 2026-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0006_alter_price_price_close_alter_price_price_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='note',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
