# Generated by Django 6.0 on 2026-01-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0007_alter_price_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_close',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_high',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_low',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_open',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
