# Generated by Django 6.0.1 on 2026-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_logs', '0009_pair_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_close',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_high',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_low',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_open',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
